/* 
DROP TABLE STUDENTS;
DROP TABLE DEPARTMENT;
DROP TABLE STATUS;

SELECT * FROM STUDENTS;
SELECT * FROM DEPARTMENT;
SELECT * FROM STATUS ;

COMMIT;
ROLLBACK;
*/
-- 테이블 생성

CREATE TABLE STUDENTS(
	STUDENT_NO VARCHAR2(20) NOT NULL,
	STUDENT_NAME VARCHAR2(20) NOT NULL,
	STUDENT_MAJOR VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	STUDENT_STATUS VARCHAR2(20) NOT NULL,
	PHONE_NO VARCHAR2(20),
	GENDER CHAR (10),
	ADDRESS VARCHAR2(50)
);

COMMENT ON COLUMN STUDENTS.STUDENT_NO IS '학번';  
COMMENT ON COLUMN STUDENTS.STUDENT_NAME IS '학생 이름';  
COMMENT ON COLUMN STUDENTS.STUDENT_MAJOR IS '전공';  
COMMENT ON COLUMN STUDENTS.ENROLL_DATE IS '입학날짜';  
COMMENT ON COLUMN STUDENTS.STUDENT_STATUS IS '학적 상태';  
COMMENT ON COLUMN STUDENTS.PHONE_NO IS '연락처';  
COMMENT ON COLUMN STUDENTS.GENDER IS '성별';  
COMMENT ON COLUMN STUDENTS.ADDRESS IS '주소';  

ALTER TABLE STUDENT ADD CONSTRAINT FK_ST_MAJOR FOREIGN KEY (STUDENT_MAJOR)
	REFERENCES DEPARMENT PRIMARY KEY(DEPT_CODE);
ALTER TABLE STUDENT ADD CONSTRAINT FK_ST_STATUS FOREIGN KEY (STUDENT_STATUS)
	REFERENCES STATUS PRIMARY KEY(STATUS_NAME);

------------------------------------------------------------------
CREATE TABLE DEPARTMENT(
	DEPT_CODE VARCHAR2(10) PRIMARY KEY,
	DEPT_NAME VARCHAR2(30) UNIQUE
);

COMMENT ON COLUMN DEPARTMENT.DEPT_CODE IS '학과 코드';  
COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '학과명';  

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPT_CODE);
ALTER TABLE DEPARTMENT ADD CONSTRAINT U_DEPT UNIQUE (DEPT_NAME);

-------------------------------------------------------------------

CREATE TABLE STATUS(
	STATUS_CODE CHAR(5), 
	STATUS_NAME VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN STATUS.STATUS_CODE IS '학적상태 코드';  
COMMENT ON COLUMN STATUS.STATUS_NAME IS '학적상태';  

ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS PRIMARY KEY (STATUS NAME);

--------------------------------------------------------------------

INSERT INTO DEPARTMENT VALUES('001', '국어국문학과');
INSERT INTO DEPARTMENT VALUES('002', '중어중문학과');
INSERT INTO DEPARTMENT VALUES('003', '고고미술사학과');
INSERT INTO DEPARTMENT VALUES('004', '사학과');
INSERT INTO DEPARTMENT VALUES('005', '영어영문학과');
INSERT INTO DEPARTMENT VALUES('006', '독어독문학과');
INSERT INTO DEPARTMENT VALUES('007', '노어노문학과');
INSERT INTO DEPARTMENT VALUES('008', '철학과');
INSERT INTO DEPARTMENT VALUES('009', '불어불문학과');


INSERT INTO STATUS VALUES('S1', '재학');
INSERT INTO STATUS VALUES('S2', '휴학');
INSERT INTO STATUS VALUES('S3', '졸업');
INSERT INTO STATUS VALUES('S4', '수료');
INSERT INTO STATUS VALUES('S5', '수료후등록');
INSERT INTO STATUS VALUES('S6', '제적');


INSERT INTO STUDENTS VALUES ('2018001006', '홍길동', '국어국문학과', DEFAULT, 
'재학', '010-1234-1234', 'M', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2020008010', '박춘식', '철학과', DEFAULT, 
'재학', '010-1564-3479', 'M', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2015003018', '이오리', '고고미술사학과', DEFAULT, 
'휴학', '010-5864-1634', 'F', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2019005015', '베니마루', '영어영문학과', DEFAULT, 
'재학', '010-5464-4684', 'M', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2023009001', '신고', '불어불문학과', DEFAULT, 
'수료', '010-8464-5689', 'F', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2023009011', '네이마루', '불어불문학과', DEFAULT, 
'재학', '010-1234-1234', 'M', '서울시 도봉구');
INSERT INTO STUDENTS VALUES ('2018001006', '홍길동', '국어국문학과', DEFAULT, 
'졸업', '010-9416-1354', 'F', '서울시 도봉구');
