-- 1번
CREATE TABLE SER_TEST(
	ID NUMBER,
	NAME VARCHAR2(30),
	RESERVE_DATE DATE(20),
	ROOM_NUM NUMBER
);


INSERT INTO USER_TEST VALUES(1, '홍길동', '2016-01-05', 2014);
INSERT INTO USER_TEST VALUES(2, '임꺽정', '2016-02-12', 918);
INSERT INTO USER_TEST VALUES(3, '장길산', '2016-01-16', 1208);
INSERT INTO USER_TEST VALUES(4, '홍길동', '2016-03-17', 504);
INSERT INTO USER_TEST VALUES(6, '김유신', NULL, NULL);

-- 2번
UPDATE USER_TEST 
SET ROOM_NUM = '2002'
WHERE NAME = '홍길동';

DELETE FROM USER_TEST
WHERE ID = '6';


--3번
UPDATE USER_TEST 
SET ROOM_NUM = '2002';


--4번
CREATE TABLE EMPLOYEE4 AS SELECT * FROM EMPLOYEE; 

SELECT * FROM EMPLOYEE4;

--5번
SELECT * 
FROM EMPLOYEE4
WHERE HIRE_DATE < '2000-01-01';

UPDATE EMPLOYEE4
SET SALARY = SALARY + 1000000
WHERE HIRE_DATE < '2000-01-01';
SELECT * FROM EMPLOYEE4; 

--6번
UPDATE EMPLOYEE4 
SET BONUS = 0.5
WHERE DEPT_CODE IN ('D1', 'D2', 'D3', 'D4', 'D9'); 

UPDATE EMPLOYEE4 
SET BONUS = 0.5
WHERE DEPT_CODE IN 
	(SELECT DEPT_ID
	FROM DEPARTMENT  
	WHERE LOCATION_ID = 
		(SELECT LOCAL_CODE FROM LOCATION WHERE NATIONAL_CODE ='KO'));

UPDATE EMPLOYEE4 
SET BONUS = 0.5
WHERE DEPT_CODE IN 
	(SELECT DEPT_CODE
	FROM EMPLOYEE4 
	JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
	WHERE LOCATION_ID = 'L1');

UPDATE EMPLOYEE4 
SET BONUS = 0.5
WHERE DEPT_CODE IN 
	(SELECT EMP_NAME
	FROM EMPLOYEE4 
	JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
	JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
	JOIN NATIONAL USING(NATIONAL_CODE)
	WHERE NATIONAL_NAME = '한국');

ROLLBACK;

