
-- 1번 문제
SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열 
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열 
FROM TB_DEPARTMENT;


-- 2번 문제
SELECT DEPARTMENT_NAME, '정원은', CAPACITY, '명 입니다.' 
FROM TB_DEPARTMENT;


-- 3번 문제
SELECT STUDENT_NAME  
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN ='Y';


-- 4번 문제
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513__%';

-- 5번
