
-- 1번 문제
SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE
					FROM EMPLOYEE 
					WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';


-- 2번 문제
WITH HIGH_SAL AS (SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
					FROM EMPLOYEE 
					JOIN JOB USING(JOB_CODE)
					WHERE EXTRACT(YEAR FROM HIRE_DATE) > 2000)
SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM HIGH_SAL
WHERE ROWNUM = 1;

-- 3번 문제
--SELECT DEPT_CODE, JOB_CODE
--FROM EMPLOYEE 
--WHERE EMP_NAME = '노옹철';

SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
LEFT JOIN JOB USING (JOB_CODE)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
								FROM EMPLOYEE 
								WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';

-- 4번 문제
--SELECT DEPT_CODE, JOB_CODE
--FROM EMPLOYEE 
--WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, HIRE_DATE
FROM EMPLOYEE 
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
								FROM EMPLOYEE 
								WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2000);

-- 5번 문제
SELECT DEPT_CODE, MANAGER_ID
FROM EMPLOYEE 
WHERE SUBSTR(EMP_NO, 8 ,1) = '2'
AND SUBSTR(EMP_NO, 1, 2) = '77';

SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, HIRE_DATE
FROM EMPLOYEE 
WHERE (DEPT_CODE, MANAGER_ID) = (SELECT DEPT_CODE, MANAGER_ID
									FROM EMPLOYEE 
									WHERE SUBSTR(EMP_NO, 8 ,1) = '2'
									AND SUBSTR(EMP_NO, 1, 2) = '77');

-- 6번 문제
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE 
FULL JOIN JOB USING(JOB_CODE)
FULL JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE IN (SELECT MIN(HIRE_DATE)
					FROM EMPLOYEE
					WHERE ENT_YN = 'N'
					GROUP BY DEPT_CODE)
ORDER BY 5;

-- 7번 문제
WITH SAL AS (SELECT EMP_ID, EMP_NAME, JOB_NAME,
			TO_CHAR(SYSDATE, 'YYYY')- (19 || (SUBSTR(EMP_NO,1,2))) 나이,
			(((SALARY + (SALARY * NVL(BONUS,0)))* 12)) 보너스포함연봉
			FROM EMPLOYEE 
			JOIN JOB USING (JOB_CODE))
SELECT EMP_ID, EMP_NAME, JOB_NAME, 나이, 보너스포함연봉
FROM SAL MAIN
WHERE 나이 = (SELECT MIN(나이) 
				FROM SAL SUB
				WHERE SUB.JOB_NAME = MAIN.JOB_NAME)
ORDER BY 나이 DESC;



